export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_PRODUCT_DETAILS = 'EDIT_PRODUCT_DETAILS';
export const UPDATE_PRODUCT_DETAILS = 'UPDATE_PRODUCT_DETAILS';
export const DELETED_PRODUCT = 'DELETED_PRODUCT';