export const MOVE = "MOVE"
export const RESIZE = "RESIZE"
export const ROTATE = "ROTATE"
export const UPDATE_TRANSFORM_STATUS = "UPDATE_TRANSFORM_STATUS"
export const RESIZE_UPDATE = "RESIZE_UPDATE"
export const MOVE_UPDATE = "MOVE_UPDATE"
export const ROTATE_UPDATE = "ROTATE_UPDATE"